version: '3'
services:
  pgsql:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
